# runtime: python37
# service: api
# handlers:
# - url: /static
#   static_dir: static/
# - url: /.*
#   script: auto

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT sales_predictions.wsgi

# beta_settings:
#     cloud_sql_instances: sales-prediction

runtime_config:
  python_version: 3
